### ISSUE TITLE
Backpack connection failing

### ISSUE THREAD

**Issue by meggoodine** [discendum/obf-moodle#2] opened 2015-02-03 23:44 UTC
We've just installed the latest version of the plugin.

I'm getting a [[verification failed]] error when I try to connect Backpack settings. It takes me to the Persona sign in page, I select my email address, and then get this error:
![verificationfailed](https://cloud.githubusercontent.com/assets/10815904/6032163/ad540c82-abba-11e4-8343-e1af470fc0f2.png)

**Comment by oinp** [comment] 2015-02-09 12:35
Unfortunately we're unable to reproduce the issue in our test environment. However, I just pushed to GitHub a new version of the plugin, which should show the error message from Mozilla Persona and also write some debugging information to PHP error log if the DEVELOPER-mode is selected in Site administration > Development > Debugging.

**Comment by meggoodine** [comment] 2015-02-10 21:01
Hi Folks

I am getting a different error message now, with debugging turned on. It’s attached.

“Backpack verification failed. Reason: audience mismatch: port mismatch”

In case it helps, we tested re-enabling the Moodle Badges plug-in and we were able to connect successfully to Mozilla from there.

Thanks

Meg

**Comment by oinp** [comment] 2015-02-11 08:39
We found an issue when the site was using HTTPS but the port wasn't specified in Moodle's configuration. That caused the port mismatch error. I just pushed a fixed version to GitHub which should resolve the issue.

**Comment by meggoodine** [comment] 2015-02-11 18:42
Success!!!!  Thanks everyone.

**Closed** 2015-02-12 06:50 UTC
